<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>versionList</name>
   <tag></tag>
   <elementGuidId>5458da75-acca-424f-8015-a160493f80d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='version-list']/tbody/tr/td[text()='2/1/2006']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='version-list']/tbody/tr/td[text()='2/1/2006']</value>
   </webElementProperties>
</WebElementEntity>
