<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PositionsFlow</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b425b26c-c704-4b7f-bb73-6cb62a63ef4b</testSuiteGuid>
   <testCaseLink>
      <guid>a309b041-c5ea-48e9-ae2a-df7889d8b62f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positions/TC_CreatePosition</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>260517d7-a2f4-4e4a-bf0e-9ae7c546b2d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53b33430-9897-4b98-8c60-2333a28f427c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4b12294-36d4-4bed-9217-b8f8c6cce08a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6dfd239-b807-4532-ad38-09855b60fff1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee28aa3f-6bd1-40be-b144-b6ffbf866f72</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eeb7dee1-dbdd-484e-bb02-0fc5f542396c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positions/TC_Advanced SearchPosition</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c4bbc00-ec2b-4a7f-a76e-797e432e2e75</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
