<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete_UnitTypes</name>
   <tag></tag>
   <elementGuidId>0d12711d-a38b-4e14-b61c-69bd5f1cc708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='summary-view']//span[@title='Delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='summary-view']//span[@title='Delete']</value>
   </webElementProperties>
</WebElementEntity>
