<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Okbutton_calendar</name>
   <tag></tag>
   <elementGuidId>4aec675d-bcef-4396-8ba4-fe23d0b28839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@role='dialog']//button[@title='Ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@role='dialog']//button[@title='Ok']</value>
   </webElementProperties>
</WebElementEntity>
