<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PlansHeading</name>
   <tag></tag>
   <elementGuidId>db41ae61-a98a-418b-adff-ad6743d3120e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='sectionhead']//h2[text()='Plans']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='sectionhead']//h2[text()='Plans']</value>
   </webElementProperties>
</WebElementEntity>
