<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Period_OK_Button</name>
   <tag></tag>
   <elementGuidId>6e0bc272-f61c-4407-a189-5aa5bb983bff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='ui-button-text'][text()='Ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@class='ui-button-text'][text()='Ok']</value>
   </webElementProperties>
</WebElementEntity>
