<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StartDate_Period_Search</name>
   <tag></tag>
   <elementGuidId>c92be684-f5d7-4a85-8cde-52050655ffa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='s2id_autogen12_search'][@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='s2id_autogen12_search'][@type='text']</value>
   </webElementProperties>
</WebElementEntity>
