<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add-Icon</name>
   <tag></tag>
   <elementGuidId>f1b9ca08-80e0-46a8-8ff6-c45a51e2c6a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='tools']//div[@class='singleIconContainer']//span[@title='Add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='tools']//div[@class='singleIconContainer']//span[@title='Add']</value>
   </webElementProperties>
</WebElementEntity>
