<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Validate_BU</name>
   <tag></tag>
   <elementGuidId>2150a0b6-02cd-4d5a-8a60-99f180b1ece0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/input[@class='add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/input[@class='add']</value>
   </webElementProperties>
</WebElementEntity>
