<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StartDate_Period_Search</name>
   <tag></tag>
   <elementGuidId>2e862126-47db-4381-bd2f-fd92e2ea8ba2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type='text'][@id='s2id_autogen8_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@type='text'][@id='s2id_autogen8_search']</value>
   </webElementProperties>
</WebElementEntity>
